version: '3.9'
services:
  catalog-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: microser-catalogo:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/catalogo
    depends_on:
      - mongo
    networks:
      - microservices-network

  mongo:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: catalogo
    volumes:
      - mongo-data:/data/db
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
